# Generated by Django 3.2.8 on 2021-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0005_auto_20210510_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='entity_id',
            field=models.CharField(max_length=36),
        ),
    ]
